server:
  port: 8002
  #max-http-header-size: 1024000
  servlet: 
    context-path: /bot
spring:
  redis: 
    host: 18.212.105.77
    port: 6379
    password: tg_pass
    database: 0
    timeout: 10000
    pool: 
      max-active: 200
      max-wait: 10000 
      max-idle: 10
      min-idle: 5
backcore: 
  sendUrl: http://18.212.105.77:800/api     
websocket: 
  status: Y 
bot: 
  status: N
  token:
  username: 
  kf_chanel: 
  cz_chanel: 
  tx_chanel: 
  wf_chanel: 
  kj_chanel: 
  chatId: 123456
  filePath: 