server:
  port: 8002
  #max-http-header-size: 1024000
  servlet: 
    context-path: /api
spring:
  redis: 
    host: 18.212.105.77
    port: 6379
    password: tg_pass
    database: 0
    timeout: 10000
    pool: 
      max-active: 200
      max-wait: 10000 
      max-idle: 10
      min-idle: 5
backcore: 
  sendUrl: http://18.212.105.77      
bot: 
  token: 6724044931:AAE47iAPtnsMxdq8rnhrsJfTbVZNDp4uHuQ
  username: mengfantest_bot
  kf_chanel: https://t.me/tiantian2013
  cz_chanel: https://t.me/mimi2013,https://t.me/tiantian2013
  tx_chanel: https://t.me/tiantian2013
  wf_chanel: https://t.me/hunhunhundeceshi
  kj_chanel: https://138130.com/mobile/Lottery_code/index.html?lottery_id=308
  chatId: -1002046180926
  filePath: D:/data/pic